ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM balenalib/$BALENA_ARCH-debian-python

WORKDIR /home

RUN apt-get update -y && apt-get install build-essential
RUN pip3 install requests gpiozero paho-mqtt numpy RPi.GPIO
COPY . .

WORKDIR hx711py

CMD ["python3", "example.py"]
